name: CI

on:
  push: # 一度動作確認してActionsが動きそうならオフにする # オフにしないとpushの無限ループにおちいるよ。
  schedule:
  - cron: "* */1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: setup Node
      uses: actions/setup-node@v1
      with:
          node-version: 10.x
          registry-url: 'https://registry.npmjs.org'
    
    - name: Run a multi-line script
      run: |
        echo | ls
        node ./actions/rvh.js        
        
        git config user.name ${NAME}
        git config user.email ${EMAIL}
        git remote set-url origin https://${NAME}:${{ secrets.PASS_GITHUB }}@github.com/${NAME}/${REPO}.git
        echo git branch 
        git add . &&  git commit -m "update rvh" &&  git push origin HEAD:refs/heads/master || true
      env:
        NAME: y52en
        EMAIL: test
        REPO: test
